//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILMS()
        {
            this.SESSIONS = new HashSet<SESSIONS>();
        }
    
        public int film_id { get; set; }
        public string film_name { get; set; }
        public Nullable<System.TimeSpan> film_duration { get; set; }
        public string film_rating { get; set; }
        public string film_producer { get; set; }
        public Nullable<int> style { get; set; }
        public Nullable<int> country { get; set; }
    
        public virtual COUNTRIES COUNTRIES { get; set; }
        public virtual STYLES STYLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESSIONS> SESSIONS { get; set; }
    }
}
