//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESSIONS()
        {
            this.TICKETS = new HashSet<TICKETS>();
        }
    
        public int session_id { get; set; }
        public Nullable<int> hall_id { get; set; }
        public Nullable<System.DateTime> session_date { get; set; }
        public Nullable<System.TimeSpan> session_time { get; set; }
        public Nullable<int> film_id { get; set; }
        public Nullable<decimal> ticket_price { get; set; }
    
        public virtual FILMS FILMS { get; set; }
        public virtual HALLS HALLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETS> TICKETS { get; set; }
    }
}
