//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int ticket_id { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<int> session_id { get; set; }
        public Nullable<int> place_id { get; set; }
        public string sold_or_not { get; set; }
    
        public virtual PLACES PLACES { get; set; }
        public virtual SESSIONS SESSIONS { get; set; }
    }
}
